theme: jekyll-theme-time-machine
url: "https://admin.alhikmah.my.id" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
google-site-verification=JXWpsVjJl8ky6zLOiyiVXsa41fuOLrkK40t6kWuvfqw
